### ISSUE TITLE
On code to apply the saliency method for the Transformer model

### ISSUE THREAD

**Issue by BiEchi** [shuoyangd/tarsius#2]
Dear @shuoyangd, 
Thanks again for your great work! I'm writing to ask where I can find any supporting materials to your implementation of the saliency map applied to the Transformers model in the code [fairseq_salience.py](https://github.com/shuoyangd/fairseq/blob/6a20ebe15c2154fa31d05e2ff8457269b95cd1af/fairseq_salience.py), including tutorials, algorithm paper, etc? I have the [vanilla gradient paper applied to CNN](https://arxiv.org/pdf/1312.6034.pdf) in hand but still confused about how to transplant how apply it to a Transformer model.
Looking forward to your reply!

**Comment by shuoyangd** [comment]
Hello again!

Could you elaborate a bit about the confusion, namely, how do you find application of these methods different between CNN & Transformers? That would help me explain to you, or point you to the right material.

Shuoyang

**Comment by BiEchi** [comment]
Thanks for the reply! From the [original paper](https://arxiv.org/pdf/1312.6034.pdf) (vanilla gradient), we only need to do a backprop to get the saliency map. But this is for images; for sequence, as you stated in the paper, **the method will generate one importance score for each dimension of the word embedding, but most applications of saliency to NLP want a word-level importance score**. I'm not very sure where the code implemented this functionality in the `fairseq` dir. @shuoyangd

**Comment by BiEchi** [comment]
Closing this issue as we've found a good implementation for saliency maps: https://github.com/jalammar/ecco
Thanks a lot for the help! @shuoyangd

**Comment by shuoyangd** [comment]
Sorry for the delay. For the record, what you are talking about is not caused by the architectural difference of transformers, but rather the application/modality context in which you would like to apply sequence models to. For images, a per-dimension importance score makes sense, because it can be easily mapped to a single pixel. For NLP, we need some sort of composition because we want a word-level importance score.

In the NLP case, the composition is implemented in this repo by registering hooks for logging gradients in slightly different ways, as coded [here](https://github.com/shuoyangd/fairseq/blob/6a20ebe15c2154fa31d05e2ff8457269b95cd1af/salience.py#L246).
